services:
  - type: web
    name: jasa-instalasi-cctv
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    branch: main
    autoDeploy: true
